schema_version = "1.0.0"

id = "hotspot_base_map_generator"
version = "0.1.11"
name = "Hotspot Base Map Generator"
tagline = "Generate hotspot texture base maps for external texturing"
maintainer = "Hotspot Base Map Generator Contributors"
type = "add-on"

blender_version_min = "5.0.0"
license = ["SPDX:GPL-3.0-or-later"]
tags = ["UV", "Paint", "Import-Export"]

[build]
paths_exclude_pattern = [
  "__pycache__/",
  ".*",
  "/*.zip",
  "*.blend[1-9]",
  "dist/",
  "media/",
  "tests/",
  "tools/",
  "*.md",
  "LICENSE",
]
