ADDON_ID = "hotspot_base_map_generator"
DISPLAY_NAME = "Hotspot Base Map Generator"
IMAGE_PREFIX = "HBMG"

SPLIT_NONE = "NONE"
SPLIT_HORIZONTAL = "HORIZONTAL"
SPLIT_VERTICAL = "VERTICAL"

COLOR_MODE_RANDOM = "RANDOM"
COLOR_MODE_GRAYSCALE = "GRAYSCALE"
COLOR_MODE_STORED = "STORED"

